umbrella/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weather.urls')),
]

weather/urls.py
from django.urls import path
from weather.views import LoginUserView, SignUpView, LogoutUserView, ProfileView, UpdateUserView, HistoryView

app_name = 'weather'
urlpatterns = [
    path('', LoginUserView.as_view(), name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('logout/', LogoutUserView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/', UpdateUserView.as_view(), name='edit'),
    path('profile/history/<int:pk>/', HistoryView.as_view(), name='history')
]

weather/models.py
from django.db import models
from django.contrib.auth.models import User


class City(models.Model):
    name = models.CharField(max_length=200)
    user = models.ManyToManyField(User, related_name='cities', blank=True)
    searched_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

weather/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from weather.models import City


class SignUpForm(UserCreationForm):
    country = forms.CharField(max_length=200)

    class Meta:
        model = User
        fields = ('username', 'country', 'password1', 'password2')


class CityForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(
        attrs={"Placeholder": 'search ...'}))

    class Meta:
        model = City
        fields = ('name',)


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

weather/views.py
from django.urls import reverse
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from weather.models import City
from django.views.generic import View
from django.contrib.auth.views import LoginView
from django.views.generic import CreateView, UpdateView, ListView
from weather.forms import SignUpForm, CityForm, UserForm
from django.contrib.auth import logout
from .utils import get_data
from dotenv import load_dotenv

load_dotenv()


class SignUpView(CreateView):
    form_class = SignUpForm
    template_name = 'index.html'

    def get_success_url(self):
        return reverse('weather:login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        for key, value in get_data('tehran').items():
            context[key] = value
        return context


class LoginUserView(LoginView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['res'] = 'res'
        for key, value in get_data('tehran').items():
            context[key] = value
        return context


class ProfileView(View):

    def get(self, request):
        context = {'form': CityForm()}
        for key, value in get_data('tehran').items():
            context[key] = value
        return render(request, 'profile.html', context)

    def post(self, request):
        form = CityForm(request.POST)
        context = {'form': form}
        if form.is_valid():
            form.save()
            city = City(name=form.cleaned_data['name'])
            city.save()
            city.user.add(request.user)
            city.save()
            context['form'] = CityForm()
            try:
                for key, value in get_data(form.cleaned_data['name']).items():
                    context[key] = value
            except:
                context['error'] = 'error'
        return render(request, 'profile.html', context)


class LogoutUserView(View):
    def get(self, request):
        logout(request)
        return redirect('weather:login')


class UpdateUserView(UpdateView):
    template_name = 'edit.html'
    form_class = UserForm
    queryset = User.objects.all()

    def get_success_url(self):
        return reverse('weather:profile')


# User search history
class HistoryView(ListView):
    template_name = 'profile.html'
    model = User
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['history'] = 'history'
        context['form'] = CityForm()
        return context

    def get_queryset(self):
        user = User.objects.get(pk=self.kwargs['pk'])
        return user.cities.order_by('-searched_at')

weather/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>

    <style>
        body {
            background-color: rgb(172, 207, 240);
        }
        div {
            border-radius: 5px;
            background-color: #f2f2f2;
            padding: 35px;
            width: 50%;
            margin: auto;
            }

        input[type=text], input[type=email], select {
            width: 100%;
            padding: 12px 20px;
            margin: 10px 0;
            display: inline-block;
            border: 1px solid #ccc;
            border-radius: 4px;
            -webkit-transition: 0.5s;
            transition: 0.5s;
            outline: none;
            box-sizing: border-box;
            }

        input[type=text]:focus {
            border: 2px solid #555;
            }

        input[type=email]:focus{
            border: 2px solid #555;
        }

        input[type=submit] {
            width: 100%;
            background-color: rgb(68, 65, 228);
            color: white;
            padding: 14px 20px;
            margin: 20px auto;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            }

        input[type=submit]:hover {
            background-color: rgb(122, 135, 237);
            }

    </style>

</head>
<body>
    <div>
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <br/>
            <input type="submit", value="Save" >
        </form>
    </div> 

</body>
</html>

weather/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Weather</title>

    <style>

        #container {
            width: 95%;
            height: 700px;
            margin: auto;
        }
        #left {
            background-color: rgb(43, 116, 184);
            width: 35%;
            height: 700px;
            float: right;
            padding: 20px;
            box-sizing: border-box;
        }
        #right {
            width: 65%;
            height: 700px;
            padding: 20px;
            box-sizing: border-box;
            background-image: url('{% static "images/tehrann.jpg" %}');
            background-position: right;
        }
        
        input[type=text], input[type=password], select {
            width: 92%;
            height: 30px;
            padding: 12px 20px;
            margin-bottom: 10px;
            display: inline-block;
            border: 1px solid #ccc;
            border-radius: 4px;
            -webkit-transition: 0.5s;
            transition: 0.5s;
            outline: none;
            box-sizing: border-box;
            
            }

        input[type=text], input[type=password]:focus {
            border: 2px solid #555;
            }

        input[type=submit], input[type=button] {
            width: 20%;
            height: 30px;
            font-size: 15px;
            background-color: rgb(3, 52, 109);
            color: white;
            margin-top: 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            }

        input[type=submit]:hover {
            background-color: rgb(9, 20, 100);
            }
        
        li{
                color: rgb(61, 60, 59);
            }
            
        span{
            color: rgb(61, 60, 59);
        }

        label{
            font-size: 20px;
        }

        .details {
            width: 100%; 
            height: 55px; 
            font-size: 20px;
        }

        .icons {
            width: 8%; 
            margin-right: 7px;
        }

        .weather-img {
            width: 80%; 
            float: right;
        }

    </style>
</head>
<body>

    <div id='container'>
        <div id='left'>
            {% if res %}
                <h2>Login</h2>
            {% else %}
                <h2>Sign Up</h2>
            {% endif %}
            <form method="post">
                {% csrf_token %}
                {{form.as_p}}
                {% if res %}
                Don't have an account? <a href="{% url 'weather:signup' %}">sign up</a> first!
                <input type="submit" value="login" style="margin-left: 55%;">   
                {% else %}
                Have an account? <a href="{% url 'weather:login' %}">login</a><br/>
                <input type="submit", value="submit" >
                {% endif %}

            </form>
        </div>
        <div id='right'>

            <div style="width: 20%; height: 100px; float: left; text-align: center; font-size: 60px; margin-top: 30px; padding: 5px; box-sizing: border-box;">
                 {{name}}
            </div>
            <div style="width: 20%; height: 80px; float: left; margin-left: 60px; margin-top: 70px; font-size: 30px;">
                {{temperature}} °C
                <img style="width: 25%;" src="{% static 'images/warm.png' %}">
                
                <br/>
                <span style="font-size: 18px;"> feels like {{feels_like | title}}°C</span>
            </div>
            <div style="width: 20%; height: 185px; float: left; margin-top: 25px; font-size: 22px; margin-left: 30px;">
                    
                <div style="width: 100%; height: 135px;">

                    {% if 'rain' in description %}
                        <img class="weather-img" src="{% static 'images/rainy.png' %}">
                    {% endif %}
                    {% if 'cloud' in description %}
                        <img class="weather-img" src="{% static 'images/cloudy.png' %}">
                    {% endif %}
                    {% if 'sun' in description %}
                        <img class="weather-img" src="{% static 'images/sunny.png' %}">
                    {% endif %}
                    {% if 'snow' in description %}
                        <img class="weather-img" src="{% static 'images/snowy.png' %}">
                    {% endif %}
                    {% if 'clear' in description %}
                        <img class="weather-img" src="{% static 'images/clear-sky.png' %}">
                    {% endif %}
                    {% if 'mist' in description %}
                        <img class="weather-img" src="{% static 'images/mist.png' %}">
                    {% endif %}
                    {% if 'haze' in description %}
                        <img class="weather-img" src="{% static 'images/haze.png' %}">
                    {% endif %}
                    {% if 'smoke' in description %}
                           <img class="weather-img" src="{% static 'images/smoke.png' %}">
                    {% endif %}
                    {% if 'dust' in description %}
                           <img class="weather-img" src="{% static 'images/dust.png' %}">
                    {% endif %}
                </div>
                <div style="width: 100%; height: 50px; padding-top: 10px; padding-left: 20px;">
                    {{description | title}}
                </div>                      
            </div>

            <div style="width: 40%; height: 400px;margin-left: 10%; margin-top: 200px;">
                <div class="details">
                    <div style="float: right;"><img  class="icons" src="{% static 'images/countries.png' %}">
                        Country: {{country}}
                    </div>
                    
                </div>
                <div class="details">
                    <div style="float: right;"><img  class="icons" src="{% static 'images/pressure.png' %}">
                        Pressure: {{pressure}} hPa
                    </div>
                    
                </div>
                <div class="details">
                    <div style="float: right;"><img  class="icons" src="{% static 'images/humidity.png' %}">
                        Humidity: {{humidity}}%
                    </div>
                </div>
                <div class="details">
                    <div style="float: right;"><img  class="icons" src="{% static 'images/sunrise.png' %}">
                        Sunrise: {{sunrise}}
                    </div>
                    
                </div>
                <div class="details">
                    <div style="float: right;"><img  class="icons" src="{% static 'images/sunset.png' %}">
                        Sunset: {{sunset}}
                    </div>
                    
                </div>
                <div class="details">
                    <div style="float: right;"><img  style="width: 7%; margin-right: 7px;" src="{% static 'images/windy.png' %}">
                        Windspeed: {{windspeed}} m/s NW
                    </div>
                    
                </div>
            </div> 



        </div>
    </div>

</body>
</html>

weather/templates/profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Profile</title>

    <style>
        #wrapper{
            width: 100%;
            height: 800px;
            background-color: cadetblue;
        }
        .sidebar {
            margin: 0;
            padding: 0;
            width: 15%;
            background-color: rgb(98, 154, 218);
            position: fixed;
            height: 800px;
            overflow: auto;
        }

        #else {
            width: 85%;
            background-color: rgb(172, 207, 240);
            height: 800px;
            float: right;
            background-image: url('{% static "images/mana.png" %}');
            background-position: right;
        }

            .sidebar a {
            display: block;
            color: black;
            font-size: 22px;
            padding: 16px;
            text-decoration: none;
            border: 1px solid rgb(170, 170, 170)
        }
            
            .sidebar a.active {
            background-color: rgb(3, 52, 109);
            color: white;
        }

            .sidebar a:hover:not(.active) {
            background-color:rgb(3, 52, 109);

            color: white;
        }

        #search {
            width: 100%;
            height: 100px;
            text-align: right;
            padding: 30px;
            box-sizing: border-box;
        }
        input[type=text] {
            width: 30%;
            height: 15px;
            padding: 7px;
            font-size: larger;
        }
        input[type=submit] {
            height: 25px;
            margin-left: 10px;
            width: 10%;
            font-size: 15px;
            background-color: rgb(3, 52, 109);
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            }

        input[type=submit]:hover {
            background-color: rgb(122, 135, 237);
            }
        
        label {
            display: none;
        }

        .details {
            width: 100%; 
            height: 55px; 
            font-size: 20px;
        }

        .icons {
            width: 8%; 
            margin-right: 7px;
        }

        .weather-img {
            width: 80%; 
            float: right;
        }

        #error {
            width: 60%; 
            height: 500px; 
            background-color: aquamarine; 
            margin-left: 100px; 
            background-image: url('{% static "images/4044.jpeg" %}');
            background-position: center;
        }

        #history {
            width: 50%;
            height: 500px;
            margin-left: 100px;

        }
        table {
            font-family: arial, sans-serif;
            border: 1px solid rgb(230, 213, 213);
            border-collapse: collapse;
            width: 100%;
            margin-top: 50px;
            border: 1px solid black;
        } 
        
        td, th {
            text-align: left;
            padding: 8px;
        }

        table tr:nth-child(even){
            background-color: #b3c5f5;
        }

        table tr:nth-child(odd){
            background-color: rgb(203, 221, 241);
        }

        #button {
            text-align: center;
            height: 100px;
            padding-top: 50px;
        }

        #button a {
            text-decoration: none;
            display: inline-block;
            padding: 8px 16px;
        }

        #button a:hover {
            background-color: rgb(122, 135, 237);
            color: black;
        }

        .previous {
            background-color: rgb(3, 52, 109);  
            color: white;
            margin-right: 10px;
        }

        .next {
            background-color: rgb(3, 52, 109);
            color: white;
            width: 70px;
            margin-left: 10px;
        }



    </style>
</head>
<body>
    <div id='wrapper'>
        <div class="sidebar">
            <a class="active" href="#home">{{user.username}}</a>
            <a href="{% url 'weather:edit' user.pk %}">Profile</a>
            <a href="{% url 'weather:history' user.pk %}">History</a>
            <a href="{% url 'weather:logout' %}">Log out</a>
            <img style="width: 80%; margin-top: 270px; margin-left: 10%;" src="{% static 'images/weather.png' %}">
        </div>
        <div id='else'>
            <div id="search">
                <form method="post" action="{% url 'weather:profile' %}">
                    {% csrf_token %}
                    <div>{{form.as_p}}</div>
                    <input type="submit" value="Search">
                </form>    
            </div>

                {% if error %}
                    <div id='error'></div>
                {% elif history %}
                    <div id="history">
                        <div style=" width: 100%; height: 380px;">
                        <table>
                            <tr>
                                <th>City</th>
                                <th>Searched at</th>
                              </tr>
                            {% for city in object_list %}
                                <tr>
                                    <td>{{city.name}}</td>
                                    <td>{{city.searched_at}}</td>
                                </tr>
                            {% endfor %}
                        </table>
                            </div>
                        <div id="button">

                            {% if page_obj.has_previous %}
                                <a href="?page={{ page_obj.previous_page_number }}" class="previous">&laquo; Previous</a>
                            {% endif %}
                    
                            <span>
                                page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                            </span>
                    
                            {% if page_obj.has_next %}
                                <a href="?page={{ page_obj.next_page_number }}" class="next">Next &raquo;</a>
                            {% endif %}
                        </div>
                    

                    </div>

                {% else %}
                
                <div style="width: 20%; height: 100px; float: left; text-align: center; font-size: 60px; margin-top: 30px; padding: 5px; box-sizing: border-box; margin-left: 50px;">
                    {{name}}
               </div>
               <div style="width: 20%; height: 80px; float: left; margin-left: 60px; margin-top: 70px; font-size: 30px;">
                   {{temperature}}°C
                   <img style="width: 25%;" src="{% static 'images/warm.png' %}">
                   
                   <br/>
                   <span style="font-size: 18px;"> feels like {{feels_like | title}}°C</span>
               </div>
               <div style="width: 20%; height: 185px; float: left; margin-top: 25px; font-size: 22px; margin-left: 30px;">
                       
                   <div style="width: 100%; height: 135px;">
   
                       {% if 'rain' in description %}
                           <img class="weather-img" src="{% static 'images/rainy.png' %}">
                       {% endif %}
                       {% if 'cloud' in description %}
                           <img class="weather-img" src="{% static 'images/cloudy.png' %}">
                       {% endif %}
                       {% if 'sun' in description %}
                           <img class="weather-img" src="{% static 'images/sunny.png' %}">
                       {% endif %}
                       {% if 'snow' in description %}
                           <img class="weather-img" src="{% static 'images/snowy.png' %}">
                       {% endif %}
                       {% if 'clear' in description %}
                           <img class="weather-img" src="{% static 'images/clear-sky.png' %}">
                       {% endif %}
                       {% if 'mist' in description %}
                           <img class="weather-img" src="{% static 'images/mist.png' %}">
                       {% endif %}
                       {% if 'haze' in description %}
                           <img class="weather-img" src="{% static 'images/haze.png' %}">
                       {% endif %}
                       {% if 'smoke' in description %}
                           <img class="weather-img" src="{% static 'images/smoke.png' %}">
                       {% endif %}
                       {% if 'dust' in description %}
                           <img class="weather-img" src="{% static 'images/dust.png' %}">
                       {% endif %}
                   </div>
                   <div style="width: 100%; height: 50px; padding-top: 10px; padding-left: 20px;">
                       {{description | title}}
                   </div>                      
               </div>
   
               <div style="width: 40%; height: 400px;margin-left: 10%; margin-top: 200px;">
                   <div class="details">
                       <div style="float: right;"><img  class="icons" src="{% static 'images/countries.png' %}">
                           Country: {{country}}
                       </div>
                       
                   </div>
                   <div class="details">
                       <div style="float: right;"><img  class="icons" src="{% static 'images/pressure.png' %}">
                           Pressure: {{pressure}} hPa
                       </div>
                       
                   </div>
                   <div class="details">
                       <div style="float: right;"><img  class="icons" src="{% static 'images/humidity.png' %}">
                           Humidity: {{humidity}}%
                       </div>
                   </div>
                   <div class="details">
                       <div style="float: right;"><img  class="icons" src="{% static 'images/sunrise.png' %}">
                           Sunrise: {{sunrise}}
                       </div>
                       
                   </div>
                   <div class="details">
                       <div style="float: right;"><img  class="icons" src="{% static 'images/sunset.png' %}">
                           Sunset: {{sunset}}
                       </div>
                       
                   </div>
                   <div class="details">
                       <div style="float: right;"><img  style="width: 7%; margin-right: 7px;" src="{% static 'images/windy.png' %}">
                           Windspeed: {{windspeed}} m/s NW
                       </div>

                    </div>
            </div>
            {% endif %}
    </div>  
    </div>
</body>
</html>